### ISSUE TITLE
Methods on type 'JsonElement' are not accessible'.

### ISSUE THREAD

**Issue by Chauhan225** [zzzprojects/System.Linq.Dynamic.Core#410]
Following code through's error:

```csharp
List<Item> i = db.Item.Where("x => x.JsonData.GetProperty(\"Name\").GetString().Equals(\"input\")").ToList();
Following code without dynamic predicate works fine:
List<Item> i = db.Item.Where(x => x.JsonData.GetProperty("Name").GetString().Equals("input")).ToList();

Item Class:
 public class Item
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public JsonElement JsonData { get; set; }
    }
```

Stack Trace:
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, Type itType, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, ParsingConfig config, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, String predicate, Object[] args)
   at EfCorePostgresql.Program.Main(String[] args) in D:\SB\Learning\EfCorePostgresql\EfCorePostgresql\Program.cs:line 109

**Comment by JonathanMagnan** [comment]
Hello @Chauhan225 ,

Thank you for reporting, we will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Chauhan225 ,

Sorry for the delay,

Here is what my developer suggest you, to create a method on your side to support it:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Linq.Dynamic.Core;
using System.Linq.Dynamic.Core.CustomTypeProviders;
using System.Text.Json;

namespace Z.Dynamic.Core.Lab
{
    public class Template_Simple
    {
        [DynamicLinqType]
        public static class Utils
        { 
            public static string GetPropertyGetString(JsonElement jsonElement, string name)
            {
                return jsonElement.GetProperty("Name").GetString();
            }

        }
        public class Item
        {
            public long Id { get; set; }
            public string Name { get; set; }
            public string Description { get; set; }
            public JsonElement JsonData { get; set; }
        }


        public static void Execute()
        {
            JsonDocument doc = JsonDocument.Parse(" { \"Name\": \"ZZZ\" }  ");
            List<Item> customers = new List<Item>() {new Item() { JsonData = doc.RootElement } };

            var t = customers.First().JsonData.GetProperty("Name").GetString();
            var query = customers.AsQueryable()
                .Where("x => Utils.GetPropertyGetString( x.JsonData, \"Name\") == @0  ", "ZZZ" ).ToDynamicList();  
        }
    }
}
```

We might support it eventually directly built-in in the library but at this moment, we have no plan for it.

**Comment by abbasc52** [comment]
@Chauhan225 and anyone else who is looking for an alternate solution. It seems adding the type 'JsonElement' to `CustomTypeProvider` in `parserConfig` fixed this issue for me.

```c#
public class MyCustomTypeProvider : DefaultDynamicLinqCustomTypeProvider
{
    public override HashSet<Type> GetCustomTypes() =>
        new[] { typeof(JsonElement) }.ToHashSet();
}

var config = new ParsingConfig
{
    CustomTypeProvider = new MyCustomTypeProvider()
}

List<Item> i = db.Item.Where(config,"x => x.JsonData.GetProperty(\"Name\").GetString().Equals(\"input\")").ToList();
```
