### ISSUE TITLE
Trying to parse this string "a == typeof(string)" but it throws ParseException

### ISSUE THREAD

**Issue by YushanCao** [zzzprojects/System.Linq.Dynamic.Core#427]
Code to repro this issue.  Looks like the "typeof" operator is causing issue here.  How do I include the "typeof" operator in the expression string to parse?
```
// This lambda expression works.
Func<Type, bool> func = (a) => a == typeof(string);
Console.WriteLine(func(typeof(string)));

ParameterExpression p = Expression.Parameter(typeof(Type), "a");
// But the next line throws System.Linq.Dynamic.Core.Exceptions.ParseException     
LambdaExpression e = DynamicExpressionParser.ParseLambda(new ParameterExpression[] { p }, typeof(bool), "a == typeof(string)");

```

```
System.Linq.Dynamic.Core.Exceptions.ParseException
  HResult=0x80131500
  Message='.' or '(' or string literal expected
  Source=System.Linq.Dynamic.Core
  StackTrace:
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseTypeAccess(Type type) in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1565
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 980
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 770
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 739
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 734
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 680
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 649
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 625
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 434
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 379
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 298
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 281
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 263
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 243
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 230
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 213
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArguments() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1877
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArgumentList() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1866
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression instance) in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1639
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1049
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 770
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 739
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 734
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 680
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 649
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 625
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 444
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 379
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 298
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 281
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 263
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 243
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 230
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 213
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 152
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 67
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Users\Jonathan\Documents\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 222


```

**Comment by JonathanMagnan** [comment]
Hello @YushanCao ,

We will look at it.

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @YushanCao ,

After investigation, we choose that's currently out of the scope of this library to add a feature like this one even if it could be useful. This library is more to evaluate LINQ expression than a single expression

If your goal is to evaluate a single expression, a recommend you a more powerful library: [C# Eval Expression](https://eval-expression.net/)

```csharp
var compiled = Eval.Compile<Func<Type, bool>>("a == typeof(string)", "a");
var result = compiled(typeof(string));
```

Best Regards,

Jon
