### ISSUE TITLE
Architecture is keyword and acannot be used in query

### ISSUE THREAD

**Issue by souek88** [zzzprojects/System.Linq.Dynamic.Core#498]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
When I use "architecture" as a parameter name ParseLambda throws exception. See this example:
```
var parameterNames = new List<ParameterExpression>();
parameterNames.Add(Expression.Parameter(typeof(string), "architecture"));
var architecture = "arch1";
var parameterValues = new object[] { architecture };
var expr = System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(parameterNames.ToArray(), null, "architecture = \"arch2\"");
```
## 2. Exception

Exception message:  '.' or '(' or string literal expected
Stack trace:

```
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseTypeAccess(Type type) in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 1573
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 981
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 770
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 739
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 734
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 680
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 649
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 625
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 434
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 379
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 298
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 281
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 263
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 243
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 230
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 213
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 152
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 122
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Users\azurestef\Documents\Github\zzzprojects\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 389
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
## 3. Any further technical details
When I change "architecture" parameter name to something else (i.e. "arch") it works as expected.

**Comment by StefH** [comment]
Dear @souek88,

Can you try escaping with a `@` ?
Like:
``` c#
parameterNames.Add(Expression.Parameter(typeof(string), "@architecture"));
```

**Comment by souek88** [comment]
When I escaped it still gives me same error. So I changed my query to be also escaped and it worked ("@architecture = \"arch2\"") however '@architecture' is a new name of parameter different from 'architecture' so it actually not resolves the issue.

**Comment by StefH** [comment]
It's indeed reserved: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.architecture?view=net-5.0

You could also try to set this to false:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/src/System.Linq.Dynamic.Core/ParsingConfig.cs#L173

**Comment by StefH** [comment]
Hello @souek88, did you manage to solve your problem?

**Comment by souek88** [comment]
@StefH, thanks for help. I walkaround this issue by changing 'architecture' to something else. I couldnt manage it with 'architecture' keyword.
