### ISSUE TITLE
Parse lambda Expression<Func<TObject1, TObject2, bool>> Error

### ISSUE THREAD

**Issue by aline-almeida** [zzzprojects/System.Linq.Dynamic.Core#529]
Hi! 
I'm trying to parse an `Expression<Func<TObject1, TObject2, bool>>` from the following string `"(c1, c2) => c1.Id == c2.Id"` in my generic class `CompareRule<TObject1, TObject2>`.

I've tried this:
``` c#
var c1Param = Expression.Parameter(typeof(TObject1), "c1");
var c2Parm = Expression.Parameter(typeof(TObject2), "c2");
var exp2 = (Expression<Func<TObject1, TObject2, bool>>) DynamicExpressionParser.ParseLambda(new[ ] { c1Param, c2Parm }, typeof(bool), "(c1, c2) => c1.Id == c2.Id");
```

and I'm getting the following error:  {"')' or operator expected"}
```
StackTrace:
   at System.Linq.Dynamic.Core.Tokenizer.TextParser.ValidateToken(TokenId t, String errorMessage)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseParenExpression()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimaryStart()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
```
Am I missing something?
Thanks
Aline

**Comment by aline-almeida** [comment]
Update: Nevermind this. I've it to work by sending only the part after the arrow: "c1.Id == c2.Id"
