### ISSUE TITLE
Trouble with `EF.CompileAsyncQuery` and `OrderBy`

### ISSUE THREAD

**Issue by Mike-E-angelo** [zzzprojects/System.Linq.Dynamic.Core#541]
## 1. Description

First off, thank you for all your efforts here.  This library is super cool and adds so much value.

Secondly, I am trying to ring out as much value as possible... maybe a little _too_ much. 😆

I am currently working with `EF.CompileAsyncQuery` and have got a few things working.  However, I am running into trouble with the `OrderBy` selection when using a passed-in parameter.

This appears to work via SQL connection and all:

``` c#
await using var context = contexts.Get();
var query =	EF.CompileAsyncQuery<DbContext, string, Subject>((c, o) => c.Set<Subject>().OrderBy("Name"));
var open    = await query.Invoke(context, "not used").ToArrayAsync();
```

But this does not:

``` c#
await using var context = contexts.Get();
var query =	EF.CompileAsyncQuery<DbContext, string, Subject>((c, o) => c.Set<Subject>().OrderBy(o));
var open    = await query.Invoke(context, "Name").ToArrayAsync();
```

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
System.InvalidOperationException
The LINQ expression 'DbSet<Subject>()
    .OrderBy(
        ordering: __o, 
        args: object[] {  })' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CreateCompiledAsyncQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledAsyncEnumerableQuery`2.CreateCompiledQuery(IQueryCompiler queryCompiler, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.<>c.<EnsureExecutor>b__6_0(CompiledQueryBase`2 t, TContext c, LambdaExpression q)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam1,TParam2,TParam3,TValue](TValue& target, TParam1 param1, TParam2 param2, TParam3 param3, Func`4 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.EnsureExecutor(TContext context)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, CancellationToken cancellationToken, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, Object[] parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledAsyncEnumerableQuery`2.Execute[TParam1](TContext context, TParam1 param1)
   at 
```

## 3. Fiddle or Project

I apologize for the ginormous project/SLN and ugly code but it's what I am/was working on at the moment.  I am providing this as a starting point to see if there's something really obvious.  If not, I can provide a more targeted solution.  Gladly. 😅

https://github.com/DragonSpark/Framework/blob/5be7382fe603e3262b635bfae8a9401d5c346535/DragonSpark.Application.Testing/Entities/Queries/Composition/Dynamic/DynamicQueryParametersTests.cs#L23-L79

## 4. Any further technical details
Add any relevant detail that can help us.

Just wanted to shout my support to your efforts here... they are very much appreciated. 👍

**Comment by Mike-E-angelo** [comment]
So after spending more time on this, I am not sure that this is a supported scenario.  The `OrderBy` method dynamically creates `LambdaExpression`s at runtime, and for a compiled query I am not sure that is possible/valid as it's already compiled and therefore cannot be modified.

I am not sure exactly how you could work around it, but my experience with expression trees are limited.  Maybe there's a way to account for this in a compiled expression?

**Comment by StefH** [comment]
@Mike-E-angelo 
Can you provide a complete working example console-app project ?

**Comment by Mike-E-angelo** [comment]
WOOF!  Pardon the bag of 💩 I threw over to your side @StefH 😅  I've been spending the morning trying to decipher what the actual heck I was talking about when I created this.

Anyways, I was able to create a repro for you here:
https://github.com/Mike-E-angelo/Stash/blob/e725f2e19e5695f5c72427ede077b0ca420c47f7/EfCore.CompiledQueries.zzzProjects/EfCore.CompiledQueries.BasicExpression/Worker.cs#L32

Running the project should throw the exception for you.  Please let me know if you have any issues/questions and I will further assist. 👍
