### ISSUE TITLE
Net6 incompatibility

### ISSUE THREAD

**Issue by JPVenson** [zzzprojects/System.Linq.Dynamic.Core#555]
## 1. Description
It seems like System.Linq.Dynamic.Core is currently not able to discover the correct extension methods as Net6 does add some new LINQ extensions.

## 2. Exception
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'System.Linq.Dynamic.Core.DynamicQueryableExtensions' threw an exception.
 ---> System.Exception: Specific method not found: FirstOrDefault
 ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.GetMethod(String name, Int32 parameterCount, Func`2 predicate)
   --- End of inner exception stack trace ---
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.GetMethod(String name, Int32 parameterCount, Func`2 predicate)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions..cctor()
   --- End of inner exception stack trace ---
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.All(IQueryable source, ParsingConfig config, String predicate, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.All(IQueryable source, String predicate, Object[] args)
   at Morestachio.Linq.DynamicLinq.All[T](IEnumerable`1 sourceCollection, String predicate, Object[] arguments) in H:\Code\morestachio\Morestachio.Linq\DynamicLinq.cs:line 191
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
```

**Comment by StefH** [comment]
@JPVenson 
Can you please provide the full c# code you are using ?

**Comment by JPVenson** [comment]
@StefH I will close the issue because the problem cannot be reproduced after a manual clean of bin & obj folder. Possibly an old cached dll in the output directory that caused the issue after the upgrade to Net6.
