### ISSUE TITLE
"Failed to compare two elements in the array." System.InvalidOperationException (V1.2.19 compared to V1.2.18)

### ISSUE THREAD

**Issue by michaeldye79** [zzzprojects/System.Linq.Dynamic.Core#617]
Hello all,

We've come across a [new] exception being thrown having upgraded V1.2.18 >> V1.2.19:

Exception: System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.EntryPointNotFoundException: Entry point was not found.
   at System.Collections.IComparer.Compare(Object x, Object y)
   at System.Collections.Generic.IComparer`1\[\[System.DateTime\, System.Private.CoreLib\, Version=6.0.0.0\, Culture=neutral\, PublicKeyToken=7cec85d7bea7798e\]\]_OURAPI.Utilities.AlphanumComparator.Compare(DateTime , DateTime )
   at System.Linq.EnumerableSorter`2.CompareAnyKeys(Int32 index1, Int32 index2)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer)
   at System.MemoryExtensions.Sort[T](Span`1 span, Comparison`1 comparison)
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OURAPI.Pagination.PaginationSort.ApplySort[T](SortedResults`1 results, String orderByQueryString, String defaultSort)

As in; it works without a hiccup in V1.2.18; but throws the above in V1.2.19.

The code in question is:

results.Data = d.OrderBy(orderQueryBuilder.ToString(), new AlphanumComparator()).ToList();

where our alpha numeric comparator is defined as:

public class AlphanumComparator : System.Collections.Generic.IComparer<object>

Not sure what we're doing wrong; the order by query can indeed be for string items, date/time, numeric etc.  But thought this was the correct approach to provide a comparator that'd sort out alphanumeric strings.

Any help appreciated - ta, Dr Michael Dye.

**Comment by StefH** [comment]
Can you try to extend `AlphanumComparator` from `IComparer`?

Like is done here:
https://github.com/zzzprojects/System.Linq.Dynamic.Core/blob/master/test/System.Linq.Dynamic.Core.Tests/QueryableTests.OrderBy.cs#L43

**Comment by StefH** [comment]
Note that in the version `v1.2.18`, the OrderBy did not use the comparer correctly, this was fixed in:
- https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/548
- https://github.com/zzzprojects/System.Linq.Dynamic.Core/issues/565

**Comment by StefH** [comment]
@michaeldye79 
Can you provide a full working console-app project ?

**Comment by michaeldye79** [comment]
Hi - is this any good?

[DynamicSortTest.zip](https://github.com/zzzprojects/System.Linq.Dynamic.Core/files/9242417/DynamicSortTest.zip)

**Comment by StefH** [comment]
Yes. I think I did find the bug, now I need to solve it...

**Comment by StefH** [comment]
@michaeldye79 

I think I solved it, see this PR: https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/619

Can you download this branch and test it? Or do you need a MyGet preview version to test?

**Comment by michaeldye79** [comment]
Wow thanks... Not done branch download before but will try first thing in the morning (GMT+1) and let you know. Ta.

**Comment by StefH** [comment]
A preview can be downloaded from MyGet:
https://www.myget.org/F/system-linq-dynamic-core/api/v3/index.json

See this link on how to use MyGet:
https://github.com/WireMock-Net/WireMock.Net/wiki/MyGet-preview-versions

**Comment by michaeldye79** [comment]
Morning! Yes - definitely fixed - the sort works fine.  Brill; thanks.

As we're still developing I'll use this patch if that's ok until the next "proper" release happens?

Ta, Michael.
