### ISSUE TITLE
With UseParameterizedNamesInDynamicQuery, can't  compare DateTimeOffset with String

### ISSUE THREAD

**Issue by neilbgr** [zzzprojects/System.Linq.Dynamic.Core#645]
## 1. Description
When `UseParameterizedNamesInDynamicQuery = true` in config (for best perfs), can not compare `DateTimeOffset?` with `String` anymore (even `DateTimeOffset`).

## 2. Exception
```
System.Linq.Dynamic.Core.Exceptions.ParseException
 Message         : Operator '=' incompatible with operand types 'DateTimeOffset?' and 'String'
 StackTrace      :    at System.Linq.Dynamic.Core.Parser.ExpressionParser.CheckAndPromoteOperands(Type signatures, TokenId opId, String opName, Expression& left, Expression& right, Int32 errorPos) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 2084
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 542
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 379
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 297
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 280
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 262
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 242
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 229
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator() in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 213
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\Parser\ExpressionParser.cs:line 151
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 121
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 98
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, Type itType, Type resultType, String expression, Object[] values) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicExpressionParser.cs:line 357
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where(IQueryable source, ParsingConfig config, String predicate, Object[] args) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicQueryableExtensions.cs:line 2651
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Where[TSource](IQueryable`1 source, ParsingConfig config, String predicate, Object[] args) in C:\Dev\GitHub\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\DynamicQueryableExtensions.cs:line 2618
   at Program.Main()
```

## 3. Fiddle or Project
https://dotnetfiddle.net/UGmC2g

An idea?
Thanks.

**Comment by StefH** [comment]
@neilbgr 
For some reason, the dotnetfiddle throws an error 500.
Can you please post your code here?

**Comment by neilbgr** [comment]
```csharp
// Dynamic LINQ - neilbgr

// @nuget: System.Linq.Dynamic.Core
// @nuget: Z.EntityFramework.Classic

using System;
using System.Collections.Generic;
using System.Linq;
using System.Data.Entity;
using System.Linq.Dynamic.Core;
					
public class Program
{	
	public static void Main()
	{
		GenerateData();
		
		var context = new EntityContext();
		
		var query1 = context.Customers
			.Include(c => c.Location)
			.Where("LastContact = \"2022-11-16\"");
		query1.Dump();
		
		 query1 = context.Customers
			.Include(c => c.Location)
			.Where("Location.UpdateAt = \"2022-11-16\"");
		query1.Dump();
			
		var config = new ParsingConfig
		{
			UseParameterizedNamesInDynamicQuery = true
		};
		try
		{
			var query2 = context.Customers
				.Include(c => c.Location)
				.Where(config, "LastContact = \"2022-11-16\"");
			query2.Dump();
		}
		catch (Exception ex)
		{
			ex.Message.Dump();
		}
			
		try
		{
			var query3 = context.Customers
				.Include(c => c.Location)
				.Where(config, "Location.UpdateAt = \"2022-11-16\"");
			query3.Dump();
		}
		catch (Exception ex)
		{
			ex.Message.Dump();
		}
	}
		 
	public static void GenerateData()
    {
        var list = new List<Customer>();
        list.Add(new Customer()
        {
            Name = "Terri Lee Duffy",
            CompanyName = "ABC",
            City = "Paris",
            Phone = "333-444444",
			Location = new Location() { Name = "test" },     
			LastContact = DateTimeOffset.Parse("2022-11-14")
        });
		list.Add(new Customer()
        {
            Name = "Garry Moore",
            CompanyName = "ABC",
            City = "Paris",
            Phone = "54654-444444",
			Location = new Location() { Name = "ohter test", UpdateAt = DateTimeOffset.Parse("2022-11-16") },     
			LastContact = DateTimeOffset.Parse("2022-11-16")
        });

        using (var context = new EntityContext())
        {
            context.Customers.AddRange(list);
            context.BulkSaveChanges();
        }
	}
	
	public class EntityContext : DbContext
	{
		public EntityContext() : base(FiddleHelper.GetConnectionStringSqlServer())
		{
		}
		
		public DbSet<Customer> Customers { get; set; }
		public DbSet<Location> Locations { get; set; }
	}
	
	public class Customer
    {
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
		public Location Location { get; set; }
		public DateTimeOffset? LastContact { get; set; }
    }
	
	public class Location
    {
        public int LocationID { get; set; }
        public string Name { get; set; }
		public DateTimeOffset UpdateAt { get; set; }
    }
}```

**Comment by neilbgr** [comment]
With result:
```
Dumping object(System.Data.Entity.Infrastructure.DbQuery`1[Customer])
[
   {
   City         : Paris
   CompanyName  : ABC
   CustomerID   : 2
   LastContact  : 11/16/2022 00:00:00 +00:00
   Location     : 
               {
               LocationID  : 2
               Name        : ohter test
               UpdateAt    : 11/16/2022 00:00:00 +00:00
               }
   Name         : Garry Moore
   Phone        : 54654-444444
   }
]Dumping object(System.Data.Entity.Infrastructure.DbQuery`1[Customer])
[
   {
   City         : Paris
   CompanyName  : ABC
   CustomerID   : 2
   LastContact  : 11/16/2022 00:00:00 +00:00
   Location     : 
               {
               LocationID  : 2
               Name        : ohter test
               UpdateAt    : 11/16/2022 00:00:00 +00:00
               }
   Name         : Garry Moore
   Phone        : 54654-444444
   }
]Dumping object(String)
 Operator '=' incompatible with operand types 'DateTimeOffset?' and 'String'
Dumping object(String)
 Operator '=' incompatible with operand types 'DateTimeOffset' and 'String'
```

**Comment by StefH** [comment]
@neilbgr 
Thank you for the detailed code. It's fixed.

In some time, a new NuGet will be released.

https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/666

**Comment by neilbgr** [comment]
Great! (😅 #666 PR of the beast! 😈)
