### ISSUE TITLE
DynamicExpressionParser.ParseLambda throws NullReferenceException in Blazor

### ISSUE THREAD

**Issue by jomalbert1594** [zzzprojects/System.Linq.Dynamic.Core#650]
1. Description
ParseLambda does not work in blazor even if I use the example from the documentation

                ParameterExpression x = Expression.Parameter(typeof(int), "x");
                ParameterExpression y = Expression.Parameter(typeof(int), "y");
                LambdaExpression e = dyn.DynamicExpressionParser.ParseLambda(new ParameterExpression[] { x, y }, null, "(x + y) * 2");

2. Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Linq.Dynamic.Core.Parser.KeywordsHelper..ctor(ParsingConfig config)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser..ctor(ParameterExpression[] parameters, String expression, Object[] values, ParsingConfig parsingConfig)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParameterExpression[] parameters, Type resultType, String expression, Object[] values)

**Comment by jomalbert1594** [comment]
It was the mediator that's messing up DynamicExpressionParser.
