### ISSUE TITLE
Unable to project select to dictionary

### ISSUE THREAD

**Issue by spaciandd** [zzzprojects/System.Linq.Dynamic.Core#698]
## 1. Description
I have following code, trying to project select data to **Dictionary<string, object>** but unable to do it
``` c#
var properties = new List<string>
{
    "Continent"
};

var r = await dbContext.Countries.GroupBy($"new ({string.Join(",", properties)})")
  .Select(typeof(Dictionary<string, object>), @"x => new {
        Key.Continent,
        new object[] {
            Count(),
            Sum(Capital ?? 0),
            Average(Capital ?? 0),
            Min(Capital),
            Max(Capital)
        } as Capital,
        x.OrderBy(Capital).ToList() as ChildRows
}").ToDynamicListAsync<Dictionary<string, object>>();
```

## 2. Exception
System.Linq.Dynamic.Core.Exceptions.ParseException: 'No property or field 'Continent' exists in type 'Dictionary`2''

```
Exception message:
System.Linq.Dynamic.Core.Exceptions.ParseException
  HResult=0x80131500
  Message=No property or field 'Continent' exists in type 'Dictionary`2'
  Source=System.Linq.Dynamic.Core
  StackTrace:
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.CreateNewExpression(List`1 properties, List`1 expressions, Type newType)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNew()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAsLambda(String id)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression expression)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIdentifier()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMultiplicative()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, Type itType, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Select(IQueryable source, ParsingConfig config, Type resultType, String selector, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Select(IQueryable source, Type resultType, String selector, Object[] args)
   at SmartGrid.SmartGrid.SmartGridHelper.<TestQuery>d__1.MoveNext() 

```

**Comment by StefH** [comment]
The value returned is not a dictionary but a IEnumerable from KeyValuePairs.

This code should work:
``` csharp
var properties = new List<string>
{
	"Continent"
};

var q = new[] { new Country { Capital = 1,  Continent = "africa" }, new Country { Capital = 2,  Continent = "africa" }, new Country { Capital = 2,  Continent = "europa" }  };

var r = q.AsQueryable().GroupBy("Continent")
  .Select(typeof(KeyValuePair<string, object>), @"x => new {
        Key,
        new object[] {
            Count(),
            Sum(Capital),
            Average(Capital),
            Min(Capital),
            Max(Capital)
        } as Capital

}").ToDynamicListAsync<KeyValuePair<string, object>>();

r.Dump();

// ----

public class Country
{
	public int Capital {get;set;}
	public string Continent {get;set;}
}
```

![image](https://github.com/zzzprojects/System.Linq.Dynamic.Core/assets/249938/7066cd89-75ca-45bf-bc3f-c5862b313c1d)
