### ISSUE TITLE
"Ambiguous match found" using IncludeFilter and Dynamic Execute

### ISSUE THREAD

**Issue by szavoda** [zzzprojects/System.Linq.Dynamic.Core#708]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description

Trying to execute the following code:

``` c#
var queryResult = myContext.Execute<IEnumerable<RemittanceEntity>>("Where(x => x.DeletedOn == null).IncludeFilter(x => x.Payments)").ToList();
```

and I receive an error that the IncludeFilter is ambiguous.  When the same code is used outside of the Execute (directly against the DBSet), it works.  IncludeFilter on other entities also works with Execute. Additionally, Where with the Payments entity also works using Execute.

## 2. Exception

Exception message: "Oops! Ambiguous match found for: 'IncludeFilter'. The error occurred for expression \".\" at position 140 near \".IncludeFilter(x => x.Pay\".",

Stack trace:
```
at .(ExpressionScope , Expression , Type , String , List`1 , SyntaxNode , List`1 , Boolean )
   at .(ExpressionScope , Expression , Type , String , List`1 , Boolean , List`1 , SyntaxNode , Expression& )
   at .(ExpressionScope , SyntaxNode , Type , Expression , List`1 )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .(ExpressionScope , SyntaxNode , Expression , Boolean )
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , ExpressionScope , String , Boolean , Boolean )
   at .[](EvalContext , String , IDictionary`2 , Type , EvalCompilerParameterKind , Boolean , Boolean , Boolean )
   at Z.Expressions.EvalLinq.Execute(String code, Boolean isQueryable, Expression exp, Object[] parameters)
   at System.Linq.QueryableDynamic.Execute[TValue](IQueryable source, String expression, Object parameter)
   at DirectClaim.Claims.Core.Handlers.Queries.Remittance.GetRemittancesHandler.Handle(GetRemittancesRequest request)
   at InfinityBehavioral.Common.Data.Handlers.EfCoreRequestHandler`2.Handle(TRequest request, CancellationToken cancellationToken)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.UtcDateTimeHandler`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.EncryptionHandler`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.ValidationHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.ContextParserHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.TenantScopeEvaluationHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.AuditHandler`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.CorrelationHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Data.Handlers.PipelineBehaviors.DbTransactionWrapperHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.UtcDateTimeHandler`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.EncryptionHandler`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.ValidationHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.ContextParserHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.TenantScopeEvaluationHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.AuditHandler`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at InfinityBehavioral.Common.Cqrs.Handlers.PipelineBehaviors.CorrelationHandlerAsync`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at DirectClaim.Claims.Api.Controllers.Remittance.RemittanceController.GetRemittances(GetRemittancesRequest request) in D:\\Dev\\Infinity\\Direct Claim Repos\\DirectClaim.Claims\\DirectClaim.Claims.Api\\Controllers\
emittance\
emittanceController.cs:line 25
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at InfinityBehavioral.Common.Logging.ExceptionHandling.Middleware.ExceptionHandlingMiddleware.Invoke(HttpContext context)
```

## 4. Any further technical details
.NET Core 6

**Comment by StefH** [comment]
@JonathanMagnan 
I think this issue can be moved to Z.Expressions.EvalLinq project?

**Comment by JonathanMagnan** [comment]
Hello @szavoda ,

I created this issue in the right project; https://github.com/zzzprojects/Eval-Expression.NET/issues/145

Thank you @StefH for letting me know.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @szavoda,

You currently using a method of EF Plus. However, C# Eval is not aware of our third-party library.

You need to register the method to use `IncludeFilter` in a dynamic expression.

You can register all methods of EF Plus using the following code:

```csharp
EvalManager.DefaultContext.RegisterAssembly(typeof(Z.EntityFramework.Plus.Audit).Assembly);
```

After registering the assembly, you will now be able to use your code successfully.

Best Regards,

Jon
