### ISSUE TITLE
Cannot join with IQueryable`DynamicClass

### ISSUE THREAD

**Issue by dazinator** [zzzprojects/System.Linq.Dynamic.Core#763]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
I have two `IQueryable<DynamicClass>` objects and I am attempting to perform a join.
I have included a link to a fiddle showing the error.

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
> Types 'System.Object' and 'System.Object' are incompatible (at index -1)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.CheckOuterAndInnerTypes(ParsingConfig config, Boolean createParameterCtor, Type outerType, Type innerType, String outerKeySelector, String innerKeySelector, LambdaExpression& outerSelectorLambda, LambdaExpression& innerSelectorLambda, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Join(IQueryable outer, ParsingConfig config, IEnumerable inner, String outerKeySelector, String innerKeySelector, String resultSelector, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Join[TElement](IQueryable`1 outer, ParsingConfig config, IEnumerable`1 inner, String outerKeySelector, String innerKeySelector, String resultSelector, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.Join[TElement](IQueryable`1 outer, IEnumerable`1 inner, String outerKeySelector, String innerKeySelector, String resultSelector, Object[] args)
   at QueryExperiment.CanJoin() in C:\Users\Daz Work\RiderProjects\Transformations\Transformations.Tests\QueryExperiment.cs:line 25
```

## 3. Fiddle or Project

https://dotnetfiddle.net/ysv4fC

``

## 4. Any further technical details
Add any relevant detail that can help us.

**Comment by dazinator** [comment]
Updated the above to reference a fiddle instead. and changed the title.

**Comment by dazinator** [comment]
I fixed this, by casting the queryable to the concrete type generated at runtime rather than using `IQueryable<DynamicType>`

```
 var enumerablePersons = personsTable.ToEnumerableDynamicClass(out var dataClassType); // dataClassType is the "Type" that is created at runtime, and derives from DynamicType.     
        var queryablePersons = enumerablePersons.AsQueryable().OfType(dataClassType); // The magio sauce to cast the queryable to that type.

```

I can then join the queries as expected.
