### ISSUE TITLE
Unable to find my string extensions in static class with DynamicLinqType attribute

### ISSUE THREAD

**Issue by JvDriel** [zzzprojects/System.Linq.Dynamic.Core#831]
### **1. Description**

From version 1.3.10 to 1.3.12 extension methods on string stopped working

I get an exception:

System.Linq.Dynamic.Core.Exceptions.ParseException: No applicable method 'EmptyIfNull' exists in type 'String'

``` c#
[TestMethod]
public void GetStringFunctionTest_()
{
    var sourceStringParameter = Expression.Parameter(typeof(string), "s");
    var parsingConfig = new ParsingConfig { SupportEnumerationsFromSystemNamespace = true };
    var expression = "s.EmptyIfNull()";
    DynamicExpressionParser.ParseLambda(parsingConfig, false, [sourceStringParameter], typeof(object), expression).Compile();
}
```

``` c#
[DynamicLinqType]
public static class DynamicLinqTypeExtensions
{
    public static string EmptyIfNull(this string s)
    {
        return s ?? string.Empty;
    }
}
```
### 2. Exception
Stacktrace:
```
System.Linq.Dynamic.Core.Exceptions.ParseException: No applicable method 'EmptyIfNull' exists in type 'String'
    at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseMemberAccess(Type type, Expression expression, String id)
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParsePrimary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseUnary()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseArithmetic()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAdditive()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseShiftOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseComparisonOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLogicalAndOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseIn()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseAndOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseOrOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseLambdaOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseNullCoalescingOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.ParseConditionalOperator()
   at System.Linq.Dynamic.Core.Parser.ExpressionParser.Parse(Type resultType, Boolean createParameterCtor)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(Type delegateType, ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
   at System.Linq.Dynamic.Core.DynamicExpressionParser.ParseLambda(ParsingConfig parsingConfig, Boolean createParameterCtor, ParameterExpression[] parameters, Type resultType, String expression, Object[] values)
```
 
### 3. Fiddle or Project
Not sure if that's possible in this case

### 4. Any further technical details
Running from testproject with <TargetFramework>net8.0</TargetFramework>

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/832
