### ISSUE TITLE
Blazor Wasm Eval: System.InvalidOperationException: Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by groogiam** [zzzprojects/System.Linq.Dynamic.Core#836]
Here is what to include in your request to make sure we implement a solution as quickly as possible. 

## 1. Description
Dynamic objects created by the library throw the following exception when accessing their properties in Blazor Wasm

## 2. Exception
If you are seeing an exception, include the full exception details (message and stack trace).

```
Exception message: Unhandled exception rendering component: Operation is not valid due to the current state of the object.
Stack trace: crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not valid due to the current state of the object.
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Reflection.Emit.RuntimeGenericTypeParameterBuilder.GetGenericParameterConstraints()
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.AddAggregateToSymbolTable(NamespaceOrAggregateSymbol parent, Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetCTypeFromType(Type type)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(ICSharpBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicObject.MetaDynamic.<>c.<BindGetMember>b__2_0(MetaDynamic this, GetMemberBinder b, DynamicMetaObject e)
   at System.Dynamic.DynamicObject.MetaDynamic.CallMethodWithResult[GetMemberBinder](MethodInfo method, GetMemberBinder binder, Expression[] args, Fallback`1 fallback, Fallback`1 fallbackInvoke)
   at System.Dynamic.DynamicObject.MetaDynamic.CallMethodWithResult[GetMemberBinder](MethodInfo method, GetMemberBinder binder, Expression[] args, Fallback`1 fallback)
   at System.Dynamic.DynamicObject.MetaDynamic.BindGetMember(GetMemberBinder binder)
   at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[Func`3](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[Object,Object](CallSite site, Object arg0)
   at WasmDynamicLinq.Pages.Home.OnInitialized() in D:\source\WasmDynamicLinq\Pages\Home.razor.cs:line 49
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

## 3. Fiddle or Project
Run the home page to reproduce.
[WasmDynamicLinq.zip](https://github.com/user-attachments/files/16593155/WasmDynamicLinq.zip)

**Comment by groogiam** [comment]
I had looked at this article prior to submitting the issue. This happens in debug mode and when I have the `<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>` property set in the project file. From my limited knowledge it did not seem like the same issue. I appreciate your helping looking into this. Thanks.

**Comment by StefH** [comment]
I did not find the real issue yet, as a workaround you can use:
``` c#
var allOrderItemsDynamic = orders.AsQueryable()
            .Select("new (OrderId as Id, OrderItems.Where(w => true) as Children, null as Empty)")
            .ToDynamicList<DynamicClass>();

        foreach (var element in allOrderItemsDynamic)
        {
            object elementAsObj = element;

            var idReflection = elementAsObj.GetType().GetProperty("Id")!.GetValue(elementAsObj);
            Console.WriteLine("idReflection = " + idReflection);

            Console.WriteLine("dynamic = " + element["Id"]);
        }
```

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/838

**Comment by StefH** [comment]
@groogiam 


Can you try preview version `System.Linq.Dynamic.Core.1.4.5-preview-01`?
it's available at : https://www.myget.org/F/system-linq-dynamic-core/api/v3/index.json

**Comment by groogiam** [comment]
@StefH I'm not seeing version 1.4.5 in that feed.

![image](https://github.com/user-attachments/assets/25a15c7c-4896-4664-85dd-212b2de8ec0d)

**Comment by StefH** [comment]
Did you check the preview checkbox in VS?

![Screenshot_2024-08-18-18-20-47-625_org.mozilla.firefox.jpg](https://github.com/user-attachments/assets/23e4d0ea-6682-43cb-9713-33a5fc2dc86b)

**Comment by groogiam** [comment]
Doh! I was not paying attention and did not have the box checked. Sorry about that. I tested the new updated library on my sample and can confirm the property evaluations now work without exceptions. Thanks.
