### ISSUE TITLE
SelectMany not work over JSON

### ISSUE THREAD

**Issue by changeforan** [zzzprojects/System.Linq.Dynamic.Core#858]
## 1. Description
I want to use `SelectMany` over an object which is deserialized from a JSON but get this error:

```log
Exception has occurred: CLR/System.ArgumentException
An unhandled exception of type 'System.ArgumentException' occurred in System.Linq.Expressions.dll: 'Expression of type 'System.Object' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Object]''
```

here is my code snip

```c#
using System.Linq.Dynamic.Core;
using Newtonsoft.Json;
var json = """
    [{
        "PhoneNumbers": [
            { "Number": "123" },
            { "Number": "456" }
        ]
    },
    {
        "PhoneNumbers": [
            { "Number": "789" },
            { "Number": "012" }
        ]
    }]
""";
var people = JsonConvert.DeserializeObject(json) as IEnumerable<dynamic> ?? [];
var numbsers = people.AsQueryable().SelectMany("PhoneNumbers").ToDynamicList();
Console.WriteLine(JsonConvert.SerializeObject(numbsers));
```

## 2. Exception

```
Exception message:
Exception has occurred: CLR/System.ArgumentException
An unhandled exception of type 'System.ArgumentException' occurred in System.Linq.Expressions.dll: 'Expression of type 'System.Object' cannot be used for return type 'System.Collections.Generic.IEnumerable`1[System.Object]''
Stack trace:
at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda(Type delegateType, Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Type delegateType, Expression body, IEnumerable`1 parameters)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.SelectManyInternal(IQueryable source, ParsingConfig config, Type resultType, String selector, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.SelectMany(IQueryable source, ParsingConfig config, String selector, Object[] args)
   at System.Linq.Dynamic.Core.DynamicQueryableExtensions.SelectMany(IQueryable source, String selector, Object[] args)
   at Program.<Main>$(String[] args)
```

## 3. Fiddle or Project
[Fiddle](https://dotnetfiddle.net/P7YlPY)

## 4. Any further technical details

I found a temporary workaround is combining `Select` and LINQ like this:

```c#
public static IQueryable MySelectMany(this IQueryable source, string selector)
{
    return source.Select(selector).ToDynamicList()
        .Select(it => it as IEnumerable<object>)
        .SelectMany(it => it)
        .AsQueryable();
}
```

**Comment by StefH** [comment]
https://github.com/zzzprojects/System.Linq.Dynamic.Core/pull/859

**Comment by StefH** [comment]
@changeforan 
Native JSON support has been added, and I've also added the SelectMany.

However, I still need to upload the NuGet package.

**Comment by changeforan** [comment]
hi @StefH, thanks for the quick fix, and I am wondering if this fix also works for an object like:
```c#
var people = new List<dynamic> {
    new {
        PhoneNumbers = new [] {
            new { Number = "123" },
            new { Number = "456" }
        }
    }
};
```
for now, `SelectMany` target `PhoneNumbers` also throws the same error.
But the tricky thing is that, if the `people` is init with Anonymous Type, it works:
```c#
var people = new [] {
    new {
        PhoneNumbers = new [] {
            new { Number = "123" },
            new { Number = "456" }
        }
    }
};
```
Do you have any idea why this would happen? Thank you.
